version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - export AWS_DEFAULT_REGION=us-east-1
      - export REPOSITORY_URI=078238935473.dkr.ecr.us-east-1.amazonaws.com/spring-demo-ecr
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI

  build:
    commands:
      - echo Build started...
      - mvn clean package -DskipTests
      - docker build -t spring-demo-ecr .
      - docker tag spring-demo-ecr:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $REPOSITORY_URI:latest

artifacts:
  files:
    - '**/*'
